config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'projects/index'

  resources :projects do
    resources :tasks
  end

  root 'projects#index', as: 'home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, dependent: :destroy
  validates :name, presence: true, length: {minimum: 3}
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  def index
    @project = Project.all
  end

  def new
    @project = Project.new
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if(@project.update(project_params))
      redirect_to @project
    else
      render 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end

  def create
    @project = Project.new(project_params)

    if(@project.save)
      redirect_to @project
    else
      render 'new'
    end
  end

  private def project_params
    params.require(:project).permit(:name, :summary, :start_date, :end_date)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :authenticate_user!

  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.create(task_params)
    redirect_to project_path (@project)
  end

  def edit
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
  end

  def update
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])

    if(@task.update(task_params))
      redirect_to @project
    else
      render 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
    @task.destroy
    redirect_to project_path (@project)
  end


  private def task_params
    params.require(:task).permit(:title, :description, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projectmanagment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-bold">Project management</h5>
      <span class="p-2 text-dark"><%= link_to "Main page", home_path %></span>
      <nav class="my-2 my-md-0 mr-md-3">
        <% if user_signed_in? %>
        <span class="p-2 text-dark"><%= link_to "Create project", new_project_path %></span>
        <span class="p-2 text-dark"><%= link_to "Logout", destroy_user_session_path, method: :delete %></span>
        <% else %>
        <span class="p-2 text-dark"><%= link_to "Sign in", new_user_session_path %></span>
        <span class="p-2 text-dark"><%= link_to "Registration", new_user_registration_path %></span>
        <% end %>
      </nav>
    </div>

    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/projects/edit.html.erb
<h2>Project editing</h2>
<%= form_for :project, url: project_path(@project), method: :patch do |f| %>
  <% if @project.errors.any? %>
    <% @project.errors.full_messages.each do |msg| %>
     <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field(:name, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.label :summary %><br>
    <%= f.text_area(:summary, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.label :start_date %><br>
    <%= f.date_field(:start_date, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.label :end_date %><br>
    <%= f.date_field(:end_date, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit("Update", {:class => 'btn btn-primary'}) %>
  </p>

<% end %>

app/views/projects/index.html.erb
<h1>All project</h1>
<% @project.each do |p| %>
  <div class="alert alert-light">
    <h3><%= p.name %></h3>
    <p class="size"><%= p.summary %></p>
    <%= link_to "Open project", project_path(p), :class => 'btn btn-outline-primary btn-sm' %>
  </div>
  <hr>
<% end %>

app/views/projects/new.html.erb
<h2>Create new project</h2>
<%= form_for :project, url: projects_path do |f| %>
  <% if @project.errors.any? %>
    <% @project.errors.full_messages.each do |msg| %>
     <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field(:name, {:class => 'form-control'}) %>
  </div>
  <div class="form-group">
    <%= f.label :summary %><br>
    <%= f.text_area(:summary, {:class => 'form-control'}) %>
  </div>
  <div class="form-group inline">
    <%= f.label :start_date %><br>
    <%= f.date_field(:start_date, {:class => 'form-control'}) %>
  </div>
  <div class="form-group inline">
    <%= f.label :end_date %><br>
    <%= f.date_field(:end_date, {:class => 'form-control'}) %>
  </div>
  <div class="form-group">
    <%= f.submit("Create", {:class => 'btn btn-primary'}) %>
  </div>
<% end %>

app/views/projects/show.html.erb
<div class="text-center">
  <h1 class="display-3"><%= @project.name %></h1>
</div>
<p class="lead"><%= @project.summary %></p><br>
<div class="text-right">
  <small><p>Start date: <%= @project.start_date %> ---------> End date: <%= @project.end_date %></p></small>
  <% if user_signed_in? %>
    <%= link_to "Edit project", edit_project_path(@project), :class =>'btn btn-secondary btn-sm' %>
    <%= link_to "Delete project", project_path(@project), method: :delete, data: {confirm: "Delete project?"}, :class =>'btn btn-danger btn-sm' %>
  <% end %>
</div>
<hr>
<h2>Tasks</h2>
<% @project.tasks.each do |t| %>
  <div class="alert alert-light">
    <div class="text-right">
      <% if user_signed_in? %>
        <%= link_to "Change", edit_project_task_path(@project, t), :class =>'btn btn-outline-dark btn-sm'%>
        <%= link_to "X", [t.project, t], method: :delete, data: {confirm: "Delete task?"}, :class =>'btn btn-outline-danger btn-sm btn-circle'%>
      <% end %>
    </div>
    <h5><%= t.title %></h5>
    <p><%= t.description %></p>
    <h6><%= t.status %></h6>
  </div>
  <hr>
<% end %>
<hr>
<h2>Add task</h2>
<%= form_for ([@project, @project.tasks.build]) do |f| %>
  <% if @project.errors.any? %>
    <% @project.errors.full_messages.each do |msg| %>
     <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.label :decription %><br>
    <%= f.text_area(:description, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.label :status %><br>
    <%= f.select(:status, ['New', 'In progress', 'Done'], {}, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit("Add", {:class => 'btn btn-success'}) %>
  </p>
<% end %>

app/views/tasks/edit.html.erb
<h2>Edit task</h2>
<%= form_for :task, url: project_task_path(@task), method: :patch do |f| %>
  <% if @project.errors.any? %>
    <% @project.errors.full_messages.each do |msg| %>
     <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area(:description, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.label :status %><br>
    <%= f.select(:status, ['New', 'In progress', 'Done'], {}, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit("Change", {:class => 'btn btn-success'}) %>
  </p>
<% end %>